name: Birthdays
version: 1.0
author:
- RobinRMC
- ChatGPT by OpenAI
main: nl.rmcservers.birthdays.Birthdays
commands:
  setbirthday:
    description: Set a player's birthday
    usage: /setbirthday <player> <birthday>