name: Birthdays
version: 1.0
author:
- RobinRMC
- ChatGPT by OpenAI
main: nl.rmcservers.birthdays.Birthdays
commands:
  birthday:
    description: Manage birthdays
    usage: /<command> <subcommand> [args]
    aliases: [bd]
    subcommands:
      set:
        description: Set a player's birthday
        usage: /<command> set <player> <birthday>
      list:
        description: List all birthdays
        usage: /<command> list
      remove:
        description: Remove a player's birthday
        usage: /<command> remove <player>